global using NUnit.Framework;
global using GoogleCloudPricingCalculatorNUnit.Utilities;
global using OpenQA.Selenium;
global using OpenQA.Selenium.Chrome;
global using OpenQA.Selenium.Firefox;
global using OpenQA.Selenium.Edge;
global using OpenQA.Selenium.Safari;
global using OpenQA.Selenium.Support.UI;
global using System.Collections.Generic;
global using ExpectedConditions = SeleniumExtras.WaitHelpers.ExpectedConditions;
global using OpenQA.Selenium.Interactions;
global using GoogleCloudPricingCalculatorNUnit.PageObjects.Components.Common;
global using GoogleCloudPricingCalculatorNUnit.Utilities;
global using GoogleCloudPricingCalculatorNUnit.Core;
global using GoogleCloudPricingCalculatorNUnit.PageObjects;
global using GoogleCloudPricingCalculatorNUnit.PageObjects.Components.Calculator;
global using WebDriverManager;
global using WebDriverManager.DriverConfigs.Impl;
